Rename numpy package name to be less surprising
Old version compiled to libnumpy.so while app.d set "numpytests", so
naively renaming libnumpy.so to numpy.so would result in:
ImportError: dynamic module does not define module export function (PyInit_libnumpytests)